ADN = '''ttgaatctggctaaccccttgacttgctctggcatggcaggc
agctcaatgtcactcgatgtcaattttccccctctgtcgaaggagctagcggactacgaa
tcctatacgatacactgcctctgtgaccttcaatgaatatatgacggtgctcgaccgcgt
ggacgtccggtatcgtcctgtgccagaggaggcttttctgcctgcggccacgtttagggg
aatcgacgagtttctacttgcagagtctgacattggaacggcctctattaattttacagg
actctgaccggtcgtggccctgcccatagcccgagctcaattagtgccaaccactaacag
aacgaagagaaaacaccgatgctgcgtgactagtccgttttatatagaatcggggtacct
accagtgatcgggggtccgggactcacctaaagtaatacccgatagtctacattggggaa
ctaatcataatgtaactgcaccaggcctacacagggctcctacgttttgggagttatatg
gacatatgccctttaacggctgtgggtgtggccatagtgtgcagccacttctactc'''