ADN = '''ttgaatctggctaaccccttgacttgctctggcatggcaggc
agctcaatgtcactcgatgtcaattttccccctctgtcgaaggagctagcggactacgaa
tcctatacgatacactgcctctgtgacctcaatgaatatamtgacggtgctcgaccgcgt
ggacgtccggtatcgtcctgtgccagaggaggcttttctgcctgcggccacgtttagggg
aatcgacgagtttctacttgcagagtctgacattggaacggcctctattaattttacagg
actctgaccgmgtcgtggccctgccatagcccgagctcaattagtgccaaccactaacag
aacgaagaaaaacaccgatgctgcgtgactagtccgmttttatatagaatcggggtacct
accagtgatcgggggtccgggactcacctaaagtaatacccgatagtctacattggggaa
ctaatcataatgtaactgcaccaggcctacacagggctcctacgttttgggagttatatg
gacatatgccctttaacggctgtgggtgtggccatagtgtgcagccacttctactc''' 